# Generated by Django 3.1.7 on 2021-04-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('-history_time',)},
        ),
        migrations.AddField(
            model_name='history',
            name='action_option',
            field=models.CharField(default='contains', max_length=15),
        ),
        migrations.AddField(
            model_name='history',
            name='deleted_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='verb_option',
            field=models.CharField(default='POS', max_length=30),
        ),
    ]
