# Generated by Django 3.1.7 on 2021-04-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210411_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='advanced_search',
            field=models.BooleanField(default=False),
        ),
    ]
