# Generated by Django 3.1.1 on 2021-06-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_history_advanced_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='history_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
