# Generated by Django 3.1.7 on 2021-03-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentences',
            name='slug_c',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
